#Updated property: CRnumberFromDB
#Thu Nov 21 13:37:49 GMT+03:00 2024
AuthenticateApiPath=api/Account/authenticate
CRinquiryPath=v6/integ_gsb_mci_inquiry/GetCRInformationByCRNumber
CRnumberFromDB=1010178717
DB_Password=QVf?4BY+_19
DB_User_test=ExecOCPSQL
InquiryReason=Test tag automation 
ListingPath=requirements-management/requirements
OCP_STG_BaseUrl=https\://ocpstg.moj.gov.local\:2001
OCP_Testing_BaseUrl=https\://10.162.2.236\:2031/
Ocp-inquiryPath=api/InquiryServices/GetCommericalRecordInquiryService/
Otp=1234
PortalPass=1234
PortalUser=aosama
RAP_StagUrl_Base=https\://rapstg.moj.gov.local\:2030/
RAP_testingUrl_Base=https\://10.162.2.236\:2030/
TakamolBaseUrlforLive=https\://api.moj.gov.local/
TakamolBaseUrlforTest=https\://api-test.moj.gov.local/
Takamol_Passw0rd_Live=p8rOlIh85AcfjTZt
Takamol_Passw0rd_Test=EX0ulVjrVU5r9JAx
Takamol_Path=v1/authorize/access-token
Takamol_User_Live=OtfSZCS6QCAxStVmktRjk4Nz40YVJg7g
Takamol_User_Test=aSc5b2P909WdQi2Q6ej6tbJPFnVbYRAK
TestingDB-Url=jdbc\:sqlserver\:// 10.162.1.92;databaseName\=ExecOCPortalTST;encrypt\=true;trustServerCertificate\=true
ValidateApi_Path=api/Account/ValidateOtp


ChromeDriverPath=\src\main\resources\Drivers\chromedriver.exe
