RAP_testingUrl_Base=https://10.162.2.236:2030/
RAP_StagUrl_Base=https://rapstg.moj.gov.local:2030/
ListingPath=requirements-management/requirements

TakamolBaseUrlforTest=https://api-test.moj.gov.local/
Takamol_User_Test=aSc5b2P909WdQi2Q6ej6tbJPFnVbYRAK
Takamol_Passw0rd_Test=EX0ulVjrVU5r9JAx

TakamolBaseUrlforLive=https://api.moj.gov.local/
Takamol_User_Live=OtfSZCS6QCAxStVmktRjk4Nz40YVJg7g
Takamol_Passw0rd_Live=p8rOlIh85AcfjTZt
Takamol_Path=v1/authorize/access-token
CRinquiryPath=v6/integ_gsb_mci_inquiry/GetCRInformationByCRNumber
